### ISSUE TITLE
Dockerize the Graphwar server

### ISSUE THREAD

**Issue by germangb** [catabriga/graphwar#2]
Hi, I'm working on dockerizing the graphwar server architecture so that each Room runs inside its own container. To deploy a graphwar server you would first do:

```
$ docker-compose up
```

That would create a global server and a single room. Say you want to extend it to 8 rooms instead

```
$ docker-compose scale room=8
```

Would that be of your interest?

**Comment by catabriga** [comment]
Yes, that could be nice to simplify setting up a server. However currently the room server automatically detects if there are any empty rooms and scales the number of available rooms accordingly. I don't know how that would interact with docker, as I have never used it. But if you think it could be useful go for it.

**Comment by germangb** [comment]
I plan on working on it as a fork and only keep the server part but before I do that Im going to prepare a PR with some minor changes to the project

**Comment by catabriga** [comment]
Cool, I just had time to test today. I was looking at the code and was about to say that changing the global IP inside the Constants class was a very bad style, but investigating it I found out it was put there by me originally. I am just saying that this was a bad design by my part and no one should ever do something like this, so let's avoid this in the future =).

**Comment by germangb** [comment]
I agree, I only put it there because I saw it being done in the global server class and didn't want to edit too much
